### ISSUE TITLE
Incorrect Default log_size Value

### ISSUE THREAD

**Issue by waffleshop** [voxpupuli/puppet-windows_eventlog#12]
The default MaxSize registry value should be 1048576 instead of 1028. The registry value is in bytes. Users should only use the 1028 value when setting the Maximum log size (KB) value in MMC (Windows Event Viewer.)

**Comment by ghoneycutt** [comment]
Closing due to the age of this issue. Please feel free to re-open with a pull request. Suggest linking to some documentation around setting this value.
