### ISSUE TITLE
stdlib 6+ is unsupported

### ISSUE THREAD

**Issue by michalmiddleton** [voxpupuli/puppet-windows_eventlog#57]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Agent 6.11.1
- Ruby: built in
- Distribution: opensource puppet agent
- Module version: 4.0.0

## How to reproduce (e.g Puppet code you use)
puppet module list

## What are you seeing
puppet-windows_eventlog requires 'puppetlabs-stdlib' (>= 4.13.1 < 6.0.0).

## What behaviour did you expect instead
6.2.0 is the current version of stdlib. Stdlib version 5.x is keeping us from upgrading other modules that require version 6 for their respective upgrade dependencies.

## Any additional information you'd like to impart

**Comment by alexjfisher** [comment]
This has recently been fixed in #56

**Comment by dhoppe** [comment]
@alexjfisher Maybe we should release a new version to the Forge?
