### ISSUE TITLE
windows_eventlog requires old version of puppetlabs-registry and blocks its upgrade

### ISSUE THREAD

**Issue by michalmiddleton** [voxpupuli/puppet-windows_eventlog#60]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.15.0
- Ruby: built-in
- Distribution: RHEL 
- Module version: 3.0.0

## How to reproduce (e.g Puppet code you use)
attempt to update puppetlabs-registry

## What are you seeing
`'puppet-windows_eventlog' (v3.0.0) requires 'puppetlabs-registry' (>= 1.1.1 < 3.0.0)`

## Any additional information you'd like to impart
Current version of puppetlabs-registry is 3.1.0. Can you please support it in this module? Thank you

**Comment by ghoneycutt** [comment]
Closing as this functionality has been added in #68
