### ISSUE TITLE
validate_re fails if log_size is not a string

### ISSUE THREAD

**Issue by jrdbarnes** [voxpupuli/puppet-windows_eventlog#67]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## How to reproduce (e.g Puppet code you use)

```
windows_eventlog { 'Security':
    log_size => 209715200
}
```

## What are you seeing
Error in compilation

## What behaviour did you expect instead
log_size should accept numeric types.

## Output log
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, validate_re(): input needs to be a String, not a Integer (file: /etc/puppetlabs/code/modules/windows_eventlog/manifests/init.pp, line: 58, column: 3) (file: /etc/puppetlabs/code/environments/jb_exchangelogging/site/profile/manifests/eventlogs.pp, line: 15) on node 

## Any additional information you'd like to impart
https://github.com/voxpupuli/puppet-windows_eventlog/blob/c4ab565ad87ad773b9a8b10990bffa8970565250/manifests/init.pp#L58

Suggest this is changed to:
`validate_re("$log_size", '^\d*$','The log_size argument must be a number or a string representation of a number')`

This [link ](http://www.puppetmodule.info/github/simp/puppetlabs-stdlib/puppet_functions_ruby3x/validate_re) indicates the first argument needs to be quoted.

**Comment by ghoneycutt** [comment]
Closing as this is fixed with #68
